export const languageList = {
    russian: {
        win: "Победа!",
        title: "Память",
        start: "Начать игру",
        date: "Дата",
        try: "Попытки",
        time: "Время",
        userTime: "Ваше время",
        userTry: "Количество попыток",
        pageTitle: "Игра \"Память\"",
        changeLanguage: "Изменить язык",
        info: "Для просмотра статистики завершите хотя бы одну игру",
        theme: "Изменить тему"
    },
    english: {
        win: "Victory!",
        title: "Memory",
        start: "Start the game",
        date: "Date",
        try: "Attempts",
        time: "Time",
        userTime: "Your time",
        userTry: "Number of attempts",
        pageTitle: "Memory game",
        changeLanguage: "Change the language",
        info: "Finish at least one game to view statistics",
        theme: "Change theme"
    },
    chine: {
        win: "勝利!",
        title: "記憶",
        start: "開始遊戲",
        date: "日期",
        try: "嘗試",
        time: "時間",
        userTime: "你的時間",
        userTry: "嘗試次數",
        pageTitle: "記憶遊戲",
        changeLanguage: "更改語言",
        info: "完成至少一場比賽以查看統計數據",
        theme: "改變主題"
    },
    arabe: {
        win: "فوز!",
        title: "ذاكرة",
        start: "ابدأ اللعبة",
        date: "تاريخ",
        try: "محاولات",
        time: "زمن",
        userTime: "وقتك",
        userTry: "عدد المحاولات",
        pageTitle: "لعبة الذاكرة",
        changeLanguage: "تغيير اللغة",
        info: "قم بإنهاء لعبة واحدة على الأقل لعرض الإحصائيات",
        theme: "غير الخلفية"
    },
    german: {
        win: "Sieg!",
        title: "Speicher",
        start: "Starte das Spiel",
        date: "Datum",
        try: "Versuche",
        time: "Zeit",
        userTime: "Deine Zeit",
        userTry: "Anzahl der Versuche",
        pageTitle: "Memory-Spiel",
        changeLanguage: "Ändere die Sprache",
        info: "Beende mindestens ein Spiel, um Statistiken anzuzeigen",
        theme: "Thema ändern"
    },
    spanish: {
        win: "Victoria!",
        title: "Memoria",
        start: "Empieza el juego",
        date: "fecha",
        try: "Intentos",
        time: "Tiempo",
        userTime: "Su tiempo",
        userTry: "Número de intentos",
        pageTitle: "Juego de memoria",
        changeLanguage: "Cambia el idioma",
        info: "Termina al menos un juego para ver las estadísticas",
        theme: "Cambiar de tema"
    }
}